pipeline {
    
        agent any
        environment {
            VERSION_TAG = getVersion()
        }
		stages {
			stage ('Stage 1  - Checkout') {
			    steps{
				 checkout([$class: 'GitSCM', branches: [[name: '*/main']], 
				doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], 
				userRemoteConfigs: [[credentialsId: 'e69ff7f5-1d77-48c6-9f2c-b2123caac355',
				url: 'https://github.com/echrysanthakopou/frontEnd']]]) 
			}
			}
			stage ('Stage 2 - Download dependance') {
			steps{
				sh "cd frontEnd; npm install"
			}
			}

			stage('Stage 3 -build')
			{steps{

				
				sh """ cd frontEnd;npm run build """
			}}
			stage('stage 4 - package create war')
			{steps{

				
				sh " cd frontEnd; mvn package"
			}}

			stage('stage 5 - create docker')
			{steps{

				sh "cd frontEnd; docker build . -t echrysanthakopou/front:1_0_0"
			}}

			stage('stage 6 - docker push to docker hub')
			{steps{

                sh "docker login -u echrysanthakopou -p Evelin1234!@#\$"
				sh "cd frontEnd;docker push  echrysanthakopou/front:1_0_0"
			}}


			stage('Stage 7 deploy to the server')
			{steps{
			
			ansiblePlaybook installation: 'ansible', playbook: 'deploy.yml'
			
			    
			}}

			stage('Store Artifacts')
			{steps{
				archiveArtifacts allowEmptyArchive: false, artifacts: 
				'frontEnd/target/*.war', caseSensitive: true, defaultExcludes: true,
   				fingerprint: false, onlyIfSuccessful: false 
			}}
		}
}


def getVersion(){
    def  version=sh returnStdout: true, script: 'git rev-parse --short HEAD'
    return version
}
