pipeline {
    
        agent any
        environment {
            VERSION_TAG = getVersion()
        }
		stages {
			stage ('Stage 1 - Checkout Code') {
			    steps{
				checkout([$class: 'GitSCM', branches: [[name: '*/main']], 
					doGenerateSubmoduleConfigurations: false, extensions: [], 
					submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'e69ff7f5-1d77-48c6-9f2c-b2123caac355', 
					url: 'https://github.com/echrysanthakopou/backend.git']]]) 
			}
			}
			stage ('Stage 2 - clean environment') {
			steps{
				sh " mvn clean"
			}
			}

			stage('Stage 3 - build')
			{steps{

				sh "mvn clean install"
			}}

			stage('Stage 4 - build backecnd docker')
			{steps{

				sh "docker build . -t echrysanthakopou/back:1_0_0"
			}}

			stage('Stage 5 - docker push in docker hub')
			{steps{

                sh "docker login -u echrysanthakopou -p Evelin1234!@#\$"
				sh "docker push  echrysanthakopou/back:1_0_0"
			}}


			stage('Stage 6 deploy on the server')
			{steps{
			    
		
			
			ansiblePlaybook installation: 'ansible', playbook: 'deploy.yml'
			    
			}}


			stage('Stage 7 Store Artifacts')
			{steps{
				archiveArtifacts allowEmptyArchive: false, artifacts: 'target/*.jar',
					caseSensitive: true, defaultExcludes: true, fingerprint: false,
					onlyIfSuccessful: false 
			}}
		}
}


def getVersion(){
    def  version=sh returnStdout: true, script: 'git rev-parse --short HEAD'
    return version
}
